name: Build and deploy Fullstack app to VPS

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    name: Building images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Web image
        uses: docker/build-push-action@v2
        with:
          context: ./apps/web
          file: ./apps/web/Dockerfile
          push: true
          tags: lequocuy/skillswap-web:latest

      - name: Build and push API image
        uses: docker/build-push-action@v2
        with:
          context: ./apps/api
          file: ./apps/api/Dockerfile
          push: true
          tags: lequocuy/skillswap-api:latest

  migration:
    name: Migration Database
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Apply all pending migrations to the database
        run: npx prisma migrate deploy
        # run: npx prisma migrate reset -f && npx prisma db seed
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  deploy:
    name: Deploying to VPS
    runs-on: ubuntu-latest
    needs: migration

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /devops/skillswap
            docker compose pull
            docker compose up -d